[global]
    p: 3600
    http-only
    e2dsa
    e2ts
    z, qr
    ipa: 127.0.0.1,192.168.0.0/16

[accounts]
    me: securepassword
    viewer: 123456

[/]
    /home/funnsam/copyparty
    accs:
        rwmdA: me
        r: viewer
